### ISSUE TITLE
No HP boxes

### ISSUE THREAD

**Issue by soulmark** [kesiev/stampadia#7]
The Trapped Snake (Page #00000018931) my Ranger has no HP boxes; the space where they usually go is completely blank.
The XP boxes appear correctly.

**Comment by kesiev** [comment]
Hi soulmark! It looks like I introduced a bug in latest release. I've just fixed it on the codebase and on the project website. Let me know if it's OK!

**Comment by soulmark** [comment]
Yep, works fine now!

**Comment by kesiev** [comment]
Thank you for reporting!
